### ISSUE TITLE
Add Quit Method

### ISSUE THREAD

**Issue by Toby-Broom** [chausner/PSBoinc#1]
Hello, could you add the quit method

**Comment by chausner** [comment]
It's already supported with the QuitAsync method.

**Comment by Toby-Broom** [comment]
Sorry, didn't notice Stop-Boinc, dOH

**Comment by chausner** [comment]
Oops, was referring to the BoincRpc lib. Yes, PSBoinc supports Quit as well with Stop-Boinc.
